backend/account/urls.py
from django.urls import path
from .views import user_login, user_register, user_logout

app_name = "account"

urlpatterns = [
    path('login/', user_login, name="login"),
    path('register/', user_register, name="register"),
    path('logout/', user_logout, name="logout"),
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace="main")),
                  path('', include('account.urls', namespace="account")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/main/urls.py
from django.urls import path
from .views import home, dashboard, logs

app_name = "main"

urlpatterns = [
    path('', home, name="home"),
    path('dashboard/', dashboard, name="dashboard"),
    path('logs/', logs, name="logs"),
]

backend/templates/footer.html
<footer class="bg-dark color-light py-5">
    <p class="text-light text-center mb-0 fw-bold">This project is intended for educational purposes within the
        university setting. Any unauthorized copying
        or usage without explicit acknowledgment of the developer may result in legal consequences. Respect for
        intellectual property and adherence to ethical standards are expected.</p>
</footer>

backend/templates/header.html
{% url "main:home" as home %}
{% url "main:dashboard" as dashboard %}
{% url "main:logs" as logs %}
<header>
    <nav id="navbar"
         class="navbar navbar-expand-lg  {% if request.path == home %}bg-transparent{% else %}bg-secondary-subtle{% endif %}">
        <div class="container">
            <div class="d-flex justify-content-start align-items-center gap-2">
                <button id="navbar-toggler" class="navbar-toggler border-0 outline-0" type="button" data-bs-toggle="collapse"
                        {% if request.path == home %}onclick="navbarTogglerOnClick()"{% endif %}
                        data-bs-target="#sidebar"
                        aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand text-secondary-emphasis" href="{{ home }}">NutriTrack</a>
            </div>
            <div class="collapse navbar-collapse" id="sidebar">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 gap-3">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home %}active{% endif %}"
                           {% if request.path == home %}aria-current="page"{% endif %} href="{{ home }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home %}text-dark{% endif %} {% if request.path == dashboard %}active{% endif %}"
                           {% if request.path == dashboard %}aria-current="page"{% endif %} href="{{ dashboard }}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home %}text-dark{% endif %} {% if request.path == logs %}active{% endif %}"
                           {% if request.path == logs %}aria-current="page"{% endif %}
                           href="{{ logs }}">Logs</a>
                    </li>
                </ul>
                <div>
                    {% if user.is_authenticated %}
                        <div class="dropdown">
                            <button class="btn {% if request.path == home %}btn-secondary{% else %}btn-primary{% endif %} rounded-circle"
                                    type="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                <i class="bi bi-person-fill"></i>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end border-0 shadow">
                                {#                                <li>#}
                                {#                                    <a class="dropdown-item d-flex justify-content-start align-items-center gap-3"#}
                                {#                                       href="{% url "account:profile" %}">#}
                                {#                                        <i class="bi bi-person"></i>#}
                                {#                                        <strong>{% trans 'Profile' %}</strong>#}
                                {#                                    </a>#}
                                {#                                </li>#}
                                <li>
                                    <a class="dropdown-item d-flex justify-content-start align-items-center gap-3"
                                       href="{% url "account:logout" %}">
                                        <i class="bi bi-box-arrow-right"></i>
                                        <strong>Logout</strong>
                                    </a>
                                </li>

                            </ul>
                        </div>
                    {% else %}
                        <a class="btn  btn-secondary rounded-pill fw-bolder text-nowrap text-uppercase"
                           href="{% url "account:login" %}">Login</a>
                        <a class="btn btn-outline-secondary rounded-pill fw-bolder text-nowrap text-uppercase"
                           href="{% url "account:register" %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

backend/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>{{ Title }}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/index.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
</head>
<body>
{% if messages %}
    <div class="toast-container position-fixed top-0 end-0 p-3">
        {% for message in messages %}
            <div
                    class="toast {% if message.tags == 'error' %} bg-danger {% elif message.tags == 'info' %} bg-secondary {% elif message.tags == 'success' %} bg-success {% else %} bg-primary {% endif %}"
                    role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-body text-white">
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}
{% include 'header.html' %}
{% block content %}

{% endblock %}
{% include 'footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<script src="{% static 'assets/js/index.js' %}" rel="script"></script>
{% block script %}

{% endblock %}
</body>
</html>

backend/templates/login.html
{% extends 'index.html' %}
{% block content %}
    <main>
        <section class="container my-5">
            <form enctype="multipart/form-data" method="post" action=".">
                {% csrf_token %}
                <div class="card border-2 w-75 mx-auto">
                    <div class="card-body">
                        <div class="row row-gap-1">
                            <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                                <label class="form-label" for="username">
                                    Username
                                </label>
                                <input type="text" name="username" id="username" placeholder="enter your username"
                                       class="form-control"/>
                            </div>
                            <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                                <label class="form-label" for="password">
                                    Password
                                </label>
                                <input type="password" name="password" id="password" placeholder="********"
                                       class="form-control"/>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-0">
                        <button class="btn btn-primary w-100" type="submit" role="button">Login</button>
                        <p>Dont have an account ? <a href="{% url "account:register" %}" class="link-danger">Register</a>
                        </p>
                    </div>
                </div>
            </form>
        </section>
    </main>
{% endblock %}

backend/templates/register.html
{% extends 'index.html' %}
{% block content %}
    <main>
        <section class="container my-5">
            <form enctype="multipart/form-data" method="post" action=".">
                {% csrf_token %}
                <div class="card border-2 w-75 mx-auto">
                    <div class="card-body">
                        <div class="row row-gap-1">
                            <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <label class="form-label" for="{{ form.first_name.name }}">
                                    {{ form.first_name.label }}
                                </label>
                                {{ form.first_name }}
                            </div>
                            <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <label class="form-label" for="{{ form.last_name.name }}">
                                    {{ form.last_name.label }}
                                </label>
                                {{ form.last_name }}
                            </div>
                            <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <label class="form-label" for="{{ form.username.name }}">
                                    {{ form.username.label }}
                                </label>
                                {{ form.username }}
                            </div>
                            <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <label class="form-label" for="{{ form.email.name }}">
                                    {{ form.email.label }}
                                </label>
                                {{ form.email }}
                            </div>
                            <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <label class="form-label" for="{{ form.password1.name }}">
                                    {{ form.password1.label }}
                                </label>
                                {{ form.password1 }}
                            </div>
                            <div class="col col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                                <label class="form-label" for="{{ form.password2.name }}">
                                    {{ form.password2.label }}
                                </label>
                                {{ form.password2 }}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-0">
                        <button class="btn btn-primary w-100" type="submit" role="button">Register</button>
                        <p>Already have an account ? <a href="{% url "account:login" %}" class="link-danger">Login</a></p>
                    </div>
                </div>
            </form>
        </section>
    </main>
{% endblock %}